package szr.shared;

public class CardTexts extends java.util.ListResourceBundle {
	static final Object[][] contents = {
		{"Ász", "Ász"}, 
		{"ÁtlátszóKérdõjel", "ÁtlátszóKérdõjel"}, 
		{"ÉgSzín", "ÉgSzín"}, 
		{"CardToString", "[%c %j]"}, 
		{"ComboLerakó", "ComboLerakó"}, 
		{"Cserélõ", "Cserélõ"}, 
		{"Bármilyen_kérhetõ", "Bármilyen kérhetõ"}, 
		{"Felkiáltójel", "Felkiáltójel"}, 
		{"Fordító", "Fordító"}, 
		{"CsúcsCsoki%kj", "CsúcsCsoki%kj"}, 
		{"Tarka%kc", "Tarka%kc"}, 
		{"Jelzéskérõ%kj", "Jelzéskérõ%kj"}, 
		{"JelzéslapKérdõjel", "JelzéslapKérdõjel"}, 
		{"FöldSzín", "FöldSzín"}, 
		{"Keverõ", "Keverõ"}, 
		{"Kiosztó", "Kiosztó"}, 
		{"LáncSorozó", "LáncSorozó"}, 
		{"Lila%kc", "Lila%kc"}, 
		{"Tanösvény / NCH", "Tanösvény / NCH"}, 
		{"Újrahasznosító", "Újrahasznosító"}, 
		{"Sáv / Banda", "Sáv / Banda"}, 
		{"Kereszt / Cruce", "Kereszt / Cruce"}, 
		{"Háromszög / Triunghi", "Háromszög / Triunghi"}, 
		{"Pont / Punct", "Pont / Punct"}, 
		{"?_marcaj", "?_marcaj"}, 
		{"Sáv- / Pásová", "Sáv- / Pásová"}, 
		{"Helyi- / Miestná", "Helyi- / Miestná"}, 
		{"Kör- / Okružná", "Kör- / Okružná"}, 
		{"Háromszög / Trojuholník", "Háromszög / Trojuholník"}, 
		{"Rom / Zrúcanina", "Rom / Zrúcanina"}, 
		{"Forrás / Prameò", "Forrás / Prameò"}, 
		{"Ház / Chata", "Ház / Chata"}, 
		{"Barlang / Jaskyòa", "Barlang / Jaskyòa"}, 
		{"Kitérõ- / Významová", "Kitérõ- / Významová"}, 
		{"?_znaèka", "?_znaèka"}, 
		{"Kék", "Kék"}, 
		{"Piros", "Piros"}, 
		{"Zöld", "Zöld"}, 
		{"Sárga", "Sárga"}, 
		{"Fekete", "Fekete"}, 
		{"Színkérõ%kc", "Színkérõ%kc"}, 
		{"Továbbadó", "Továbbadó"}, 
		{"Sáv", "Sáv"}, 
		{"Kereszt", "Kereszt"}, 
		{"Kör", "Kör"}, 
		{"Háromszög", "Háromszög"}, 
		{"Négyzet", "Négyzet"}, 
		{"Barlang", "Barlang"}, 
		{"Rom", "Rom"}, 
		{"Körút", "Körút"}, 
		{"?_turistajel", "?_turistajel"}, 
		{"Átadó", "Átadó"}, 
		{"Elhúzó", "Elhúzó"}, 
		{"Húzó", "Húzó"}, 
		{"Ix", "Ix"}, 
		{"Pipa", "Pipa"}, 
		{"KettesÁtadó", "KettesÁtadó"}, 
		{"KettesElhúzó", "KettesElhúzó"}, 
		{"KettesHúzó", "KettesHúzó"}, 
		{"KettesPipa", "KettesPipa"}, 
		{"NégyesHúzó", "NégyesHúzó"}, 
		{"??_utJel", "??_utJel"}, 
		{"UtJelToString", "%jstr [Ut. %ut]"}, 
		{"Utasítójelzés-kérõ%kj", "Utasítójelzés-kérõ%kj"}, 
		{"Duplázó", "Duplázó"}, 
		{"Pipáló", "Pipáló"}, 
		{"FélPipáló", "FélPipáló"}, 
		{"??_UtSzorzoJel", "??_UtSzorzoJel"}, 
		{"UtSzorzoJelToString", "%jstr [Ut. *%utsz]"}, 
		{"Variáló", "Variáló"}, 
	};
protected Object[][] getContents() {
	return contents;
}
}
