package szr.shared;

public class InfoTexts extends java.util.ListResourceBundle {
	static final Object[][] contents = {
		{"Add_meg_a_játékos-adataida", "Add meg a játékos-adataidat és csatlakozz egy játékhoz\nvagy hirdess meg egy újat (írj be egy játéknevet)."}, 
		{"A_szerverrel_való_kapcsola", "A SzérózsaSzerverrel való kapcsolat felvételéig kis türelmet...\n"}, 
		{"HIBA!_-_Nem_sikerült_kapcs", "HIBA! - Nem sikerült kapcsolódni a SzélrózsaSzerverhez.\n Újabb próbálkozáshoz nyomd meg a 'Reload'-ot."}, 
		{"A_beírt_jelszó_nem_megfele", "A beírt jelszó nem megfelelõ.\n"}, 
		{"Ilyen_nevû_játék_nincs_meg", "Ilyen nevû játék nincs meghirdetve!\n"}, 
		{"Két_azonos_nevû_játékos_ne", "Két azonos nevû játékos nem játszhat egy játékban!\n"}, 
		{"Nem_tudsz_honnan_kiszállni", "Nem tudsz honnan kiszállni!\n"}, 
		{"Add_meg_a_játékosnevedet_m", "Add meg a játékosnevedet mielõtt játékot hirdetsz!\n"}, 
		{"Add_meg_a_játékosnevedet_m1", "Add meg a játékosnevedet mielõtt játékhoz csatlakozol!\n"}, 
		{"A_hálózati_kapcsolat_megsz", "A hálózati kapcsolat megszakadt a SzélrózsaSzerverrel!\nAz appletet újra kell indítani a 'Reload' gombbal."}, 
		{"Nem_csatlakoztál_egyik_ját", "Nem csatlakoztál egyik játékhoz sem!\n"}, 
		{"Te_vagy_az_osztó_játékos._", "Te vagy az osztó játékos. Ha már úgy látod,\nhogy mindenki csatlakozott, nyomd meg a 'Kezd' gombot!"}, 
		{"Színkérés..._n", "Színkérés...\n"}, 
		{"Iránykérés..._n", "Iránykérés...\n"}, 
		{"Jelzéskérés..._n", "Jelzéskérés...\n"}, 
		{"A_játék_már_elkezdõdött,_í", "A játék már elkezdõdött, így nem lehet hozzá csatlakozni!"}, 
		{"A_lerakásra_kiválasztott_k", "A lerakásra kiválasztott kártyának\nnem határozható meg a színe vagy a jelzése!"}, 
		{"A_kártyát_nem_rakhatod_le,", "A kártyát nem rakhatod le, mert színben vagy jelzésben\nilleszkednie kell (ha kérõlap van lerakva, akkor a kéréshez)!"}, 
		{"A_beszúrásra_kiválasztott_", "A beszúrásra kiválasztott kártyának\nnem határozható meg a színe vagy a jelzése!"}, 
		{"Beszúrni_csak_olyan,_színe", "Beszúrni csak olyan, színes turistajelzéses lapot lehet,\nami színben is és jelzésben is illeszkedik!"}, 
		{"A_lila_lapok_nem_nem_illes", "A lila lapok nem nem illeszkednek\naz extra sorozásba!"}, 
		{"A_kártyát_nem_rakhatod_le,1", "A kártyát nem rakhatod le, mert az aktuális\nextra sorozási szabályok alapján illeszkednie kell!"}, 
		{"Extra_sorozási_lehetõség_v", "Extra sorozási lehetõség van,\nilyenkor nem lehet beszúrni!"}, 
		{"A_kártyát_nem_rakhatod_le,2", "A kártyát nem rakhatod le, mert színben, jelzésben,\nvagy az extra sorozás alapján illeszkednie kell (ha kérõlap, akkor a kéréshez)!"}, 
		{"Nem_jó_a_kihúzott_kezdõlap", "Nem jó a kihúzott kezdõlap, mert nem lehet meghatározni a jelzését.\nHúzz egy másikat!"}, 
		{"Nem_jó_a_kihúzott_kezdõlap1", "Nem jó a kihúzott kezdõlap, mert színtelen.\nHúzz egy másikat!"}, 
		{"Ilyenkor_még_nem_lehet_kár", "Ilyenkor még nem lehet kártyát lerakni!\n"}, 
		{"Ilyenkor_nem_lehet_passzol", "Ilyenkor nem lehet passzolni!\n"}, 
		{"Ilyenkor_még_nem_lehet_bes", "Ilyenkor még nem lehet beszúrni!\n"}, 
		{"Mivel_lila_lapot_raktál,_n", "Mivel lila lapot raktál,\nmár más lapot ebben a körben nem tehetsz le!"}, 
		{"Így_nem_lehet_vétózni,_mer", "Így nem lehet vétózni, mert a kiválasztott kártyának\nnem határozható meg a színe vagy a jelzése!"}, 
		{"A_lila_lapokat_vétózni_csa", "A lila lapokat vétózni csak másik\nazonos jelzésû, lila kártyával lehet!"}, 
		{"Az_ilyen_jelzésû_vétózott_", "Az ilyen jelzésû vétózott kártyákat\nnem lehet még egyszer vétózni!"}, 
		{"A_sorozásra_kiválasztott_k", "A sorozásra kiválasztott kártyának\nnem határozható meg a színe vagy a jelzése!"}, 
		{"Sorozni_csak_azonos_jelzés", "Sorozni csak azonos jelzésû kártyákat lehet!\n"}, 
		{"Az_ilyen_jelzésû_lapokat_n", "Az ilyen jelzésû lapokat nem lehet sorozni!\n"}, 
		{"A_lila_lapokat_nem_lehet_s", "A lila lapokat nem lehet sorozni!\n"}, 
		{"Most_nem_lehet_beszúrni,_n", "Most nem lehet beszúrni,\nmajd passzolás után!"}, 
		{"Most_csak_kötelezõ_húzást_", "Most csak kötelezõ húzást felülbírálni tudó kártya tehetõ le,\nés színben vagy jelzésben illeszkednie kell!"}, 
		{"Kötelezõ_húzás_van_érvényb", "Kötelezõ húzás van érvényben,\nilyenkor nem lehet beszúrni!"}, 
		{"Most_nem_lehet_beszúrni,_n1", "Most nem lehet beszúrni,\nmajd kötelezõ húzás után!"}, 
		{"A_kártya_és_a_szándék_küld", "A kártya és a szándék küldése...\n"}, 
		{"Válassz_ki_egy_kártyát_nés", "Válassz ki egy kártyát\nés csak utána nyomd meg a 'Lerak'/'Soroz' gombot!"}, 
		{"Válassz_ki_egy_színben_és_", "Válassz ki egy színben és jelzésben illeszkedõ kártyát\nés csak utána nyomd meg a 'Beszúr'/'Vétó' gombot!"}, 
		{"Válassz_ki_egy_kártyát_a_s", "Válassz ki egy kártyát a sajátjaid közül!"}, 
		{"Válassz_ki_egy_kártyát_a_s1", "Válassz ki egy kártyát a sajátjaid közül\nvagy nyomd meg a 'Semmi'-t!"}, 
		{"Ilyenkor_nem_lehet_kártyát", "Ilyenkor nem lehet kártyát lerakni vagy beszúrni!\n"}, 
		{"A_szándék_küldése..._n", "A szándék küldése a SzélrózsaSzervernek...\n"}, 
		{"Válassz_egy_irányt_naz_irá", "Válassz egy irányt\naz iránykérõ listából!"}, 
		{"Válassz_egy_színt_na_színk", "Válassz egy színt\na színkérõ listából!"}, 
		{"Válassz_egy_jelzést_na_jel", "Válassz egy jelzést\na jelzéskérõ listából!"}, 
		{"Küldés..._(Végül_nem_válas", "Küldés... (Végül nem választottál kártyát.)"}, 
		{"Baj_van_a_hálózati_kapcsol", "Baj van a hálózati kapcsolattal; az érkezõ üzenetek fogadásával.\nA kapcsolat a SzélrózsaSzerverrel emiatt megszakad. :-("}, 
		{"Válassz_ki_egy_paklit_és_a", "Válassz ki egy paklit és azt, hogy\nmajd hány lapot osztasz!"}, 
		{"A_játék_már_elkezdõdött,_n", "A játék már elkezdõdött,\nígy nem lehet hozzá csatlakozni!"}, 
		{"Te_következel._nHa_most_pa", "Te következel.\nHa most passzolsz, húzol egy lapot."}, 
		{"Válassz_egy_irányt_a_kérõl", "Válassz egy irányt a kérõlistából,\nmajd nyomd meg a 'Kér' gombot!"}, 
		{"Válassz_egy_jelzést_a_kérõ", "Válassz egy jelzést a kérõlistából,\nmajd nyomd meg a 'Kér' gombot!"}, 
		{"Nyomd_meg_a_'Passz'_gombot", "Nyomd meg a 'Passz' gombot\na kezdõlap kihúzásához!"}, 
		{"Válassz_egy_kártyát!_%mire", "Válassz egy kártyát! %mire\n%ut"}, 
		{"(átadásra)", "(átadásra)"}, 
		{"(eldobásra)", "(eldobásra)"}, 
		{"Válassz_egy_kártyát_vagy_'", "Válassz egy kártyát vagy 'Semmi'-t!\n"}, 
		{"Azonos_jelzésû_lapokat_még", "Azonos jelzésû lapokat még esetleg sorozhatsz.\n%(ut)"}, 
		{"Több_lapot_már_nem_rakhats", "Több lapot már nem rakhatsz le a körben.\n%(ut)%(exs)"}, 
		{"Válassz_egy_színt_a_kérõli", "Válassz egy színt a kérõlistából,\nmajd nyomd meg a 'Kér' gombot!"}, 
		{"Várj..._most_a_többiek_vét", "Várj... most a többiek vétózhatnak.\n"}, 
		{"Te_következel._Kötelezõ_pa", "Te következel. Kötelezõ passz/húzás van érvényben:\n%ut"}, 
		{"Nem_tudni_mi,_mert_program", "Nem tudni mi, mert programhiba történt!"}, 
		{"Te_következel,_extra_soroz", "Te következel, extra sorozási lehetõséged van:\n%exs"}, 
		{"Extra_sorozási_lehetõséged", "Extra sorozási lehetõséged van:\n%exs"}, 
		{"Most_nem_te_következel._n%", "Most nem te következel.\n%(ut)%(exs)"}, 
		{"Most_nem_te_jössz,_de_eset", "Most nem te jössz, de esetleg beszúrhatsz.\n%(ut)%(exs)"}, 
		{"Most_nem_te_jössz,_de_vétó", "Most nem te jössz, de vétózhatsz!\n%(ut)%(exs)"}, 
		{"Csatlakoztál_a_játékhoz._n", "Csatlakoztál a játékhoz.\nVárj, amíg az osztó játékos el nem kezdi."}, 
		{"Csatlakozz_egy_játékhoz_va", "Csatlakozz egy játékhoz vagy hirdess meg egy újat!\n"}, 
		{"Elfogytak_a_kártyáid._nMeg", "Elfogytak a kártyáid.\nMegnyerted a játékot!"}, 
		{"Sajnos_nem_te_nyertél._n", "Sajnos nem te nyertél.\n"}, 
		{"Vége_a_játéknak,_mert_rajt", "Vége a játéknak, mert rajtad kívül\nmindenki kiszállt."}, 
		{"Baj_van_a_hálózati_kapcsol1", "Baj van a hálózati kapcsolattal!\nNem sikerült elküldeni az üzenetet."}, 
		{"Az_'ÚJ_ABLAK'_gomb_elsõ_me", "Az 'ÚJ ABLAK' gomb elsõ megnyomására\n indul a Virtuális SzélrózsaSzerver is!"}, 
		{"Kb._%sec_másodperc_múlva_l", "Kb. %sec másodperc múlva lejár az idõd! Ha addig nem teszel semmit,\nautomatikusan passzoltat a rendszer!"}, 
		{"Letelt_az_idõ._Passzoltál.", "Letelt az idõ. Passzoltál.\n"}, 
		{"Kártyalapválasztás...", "Kártyalapválasztás..."}, 
		{"A_szerverhez_nem_lehet_kap", "A SzélrózsaSzerverhez nem lehet kapcsolódni, mert túl sokan\nvannak bejelentkezve. Térj vissza késõbb!"}, 
		{"Osztás...", "Osztás..."}, 
		{"Kártyalerakás", "Kártyalerakás"}, 
		{"Kezdõlaphúzás", "Kezdõlaphúzás"}, 
		{"Nyerés", "Nyerés"}, 
		{"Passzolás", "Passzolás"}, 
		{"Beszúrás", "Beszúrás"}, 
		{"%actstr..._n", "%actstr...\n"}, 
		{"Kimaradás/kötelezõ_húzás_v", "Kimaradás/kötelezõ húzás végrehajtása...\n("}, 
		{"Érvénytelen_akció!_n", "Érvénytelen akció!\n"}, 
		{"Így,_amikor_nem_te_jössz,_", "Így, amikor nem te jössz,\nnincs értelme passzolni!"}, 
		{"Így,_amikor_nem_te_jössz,_1", "Így, amikor nem te jössz,\nkártyát csak beszúrni lehet!"}, 
		{"Így,_amikor_te_jössz,_nnem", "Így, amikor te jössz,\nnem lehet sem beszúrni, sem vétózni!"}, 
		{"A_szerverhez_nem_érkezett_", "A szerverhez nem érkezett meg a kártya, amit le akartál rakni.\nPróbáld meg újra elküldeni!"}, 
		{"Elkéstél!_%pstr_megelõzött", "Elkéstél! %pstr megelõzött.\n"}, 
		{"Keverés...", "Keverés..."}, 
		{"Érvénytelen_az_iránykérés!", "Érvénytelen az iránykérés!\n"}, 
		{"Érvénytelen_a_jelzéskérés!", "Érvénytelen a jelzéskérés!\n(Ha most kötelezõ húzás van, akkor csak halmozó jelzés kérhetõ.)"}, 
		{"Érvénytelen_a_lapkiválaszt", "Érvénytelen a lapkiválasztás!\n"}, 
		{"Érvénytelen_a_színkérés!_C", "Érvénytelen a színkérés! Csak olyan szín kérhetõ,\nami szerepel a pakliban."}, 
		{"PROGRAMHIBA!_Lépj_ki_és_tö", "PROGRAMHIBA! Lépj ki és töltsd le újra a kártyaasztalt!\n%err"}, 
		{"Nincs_kivel_csevegni_n,_me", "Nincs kivel csevegni\n, mert nem vagy bejeletkezve egyik játékba sem!"}, 
		{"A_játék_nem_hirdethetõ_meg", "A játék nem hirdethetõ meg! Lehet, hogy nem választottál\npaklit, vagy már van ilyen nevû játék meghirdetve."}, 
		{"Még_nincs_jelszókezelés,_n", "Még nincs jelszókezelés,\negyelõre mindenkinek a játékosneve a jelszava."}, 
		{"Egyedül_nem_lehet_játszani", "Egyedül nem lehet játszani!\nVárj, amíg más játékosok is csatlakoznak."}, 
		{"A_játék_nem_kezdhetõ_el,_m", "A játék nem kezdhetõ el, mert a kiválasztott\npaklit nem lehet betölteni!"}, 
		{"A_szerver_felmondta_a_kapc", "A SzélrózsaSzerver felmondta a kapcsolatot;\nvalószínûleg azért, mert leállt."}, 
		{"%exsc_SzínSorozási_lehetõs", "%exsc SzínSorozási lehetõség!"}, 
		{"Combo_Kész!__-)", "Kész! :-)"}, 
		{"Combo_Elsõ_jel__%sav", "Elsõ jel: %sav"}, 
		{"Combo_Lerakható__%jelek", "Lerakható: %jelek"}, 
		{"COMBO!_<%lev>_%istr", "COMBO! <%lev> %istr"}, 
		{"LáncSorozási_lehetõség!", "LáncSorozási lehetõség!"}, 
		{"0_lap,_csak_passzolni_kell", "0 lap, csak passzolni kell"}, 
		{"%up_lap_a_pakliból", "%up lap a pakliból"}, 
		{"%up_lapot_eldobhat_az_elõz", "%up lapot eldobhat az elõzõ játékos"}, 
		{"%uj_lapot_húzni_az_elõzõ_j", "%uj lapot húzni az elõzõ játékostól"}, 
		{"%up_a_pakliból,_%uj-t_húzn", "%up a pakliból, %uj-t húzni az elõzõ játékostól"}, 
		{"%uj-t_húzni_az_elõzõ_játék", "%uj-t húzni az elõzõ játékostól, aki még eldobhat %up lapot"}, 
		{"%uj_lapot_átad_az_elõzõ_já", "%uj lapot átad az elõzõ játékos"}, 
		{"%up_a_pakliból,_%uj_lapot_", "%up a pakliból, %uj lapot átad az elõzõ játékos"}, 
		{"%uj_lapot_átad_az_elõzõ_já1", "%uj lapot átad az elõzõ játékos és %up-t eldobhat"}, 
		{"Kötelezõ_húzás__%descr_[Ut", "Kötelezõ húzás: %descr [Ut. %ut]"}, 
		{"Programüzenet__n%err", "Programüzenet:\n%err"}, 
	};
protected Object[][] getContents() {
	return contents;
}
}
