package szr.shared;

public class WidgetTexts extends java.util.ListResourceBundle {
	static final Object[][] contents = {
		{"Fel", "Fel"}, 
		{"Le", "Le"}, 
		{"Kephiba1", "KÉP-"}, 
		{"Kephiba2", "HIBA"}, 
		{"CardSelected", "***"}, 
		{"NevLabel_text", "Játékosnév:"}, 
		{"EmailLabel_text", "E-mail cím:"}, 
		{"JelszoKuldButton_label", "Jelszó megküldése"}, 
		{"JelszoLabel_text", "Jelszó:"}, 
		{"MondButton_label", "Mond"}, 
		{"ChatLabel_text", "Cseveg\u0151"}, 
		{"UzenetLabel_text", "Üzenet:"}, 
		{"PasszButton_label", "Passz"}, 
		{"LerakButton_label", "Lerak"}, 
		{"SajatLapLabel_text", "Saját lapok:"}, 
		{"AkcioLabel_text", "Akciók:"}, 
		{"SajatSzinJelLabel_text", "Szín/jelzés:"}, 
		{"KertJelLabel1_text", "Kért"}, 
		{"KertJelLabel2_text", "jelzés:"}, 
		{"KertSzinLabel2_text", "szín:"}, 
		{"PakliJelzeslap_text1", "Pakli"}, 
		{"AzazLabel_text", "azaz:"}, 
		{"LerakottLabel_text", "Lerakott lap:"}, 
		{"PakliJelzeslap_text2", "és jelzéslap:"}, 
		{"AktSzinJelLabel3_text", "jelzés:"}, 
		{"AktSzinJelLabel2_text", "szín és"}, 
		{"AktSzinJelLabel1_text", "Aktuális"}, 
		{"JatekosLabel_text", "Játékosok:"}, 
		{"IranyLabel_text", "Irány:"}, 
		{"SmileyLabel_text", "Arcod:"}, 
		{"CardHelpButton_label", "Kártya súgó"}, 
		{"GameHelpButton_label", "Játék súgó"}, 
		{"HelpLabel1_text", "Segít-"}, 
		{"HelpLabel2_text", "ség:"}, 
		{"KertIranyLabel_text", "Kért irány:"}, 
		{"InfoLabel_text", "Infó:"}, 
		{"JatekUjButton_label", "Újat hirdet"}, 
		{"JatekCsatlButton_label", "Csatlakozik"}, 
		{"JatekLabel_text", "Játéknév:"}, 
		{"MeghirdetettLabel_text", "Meghirdetettek:"}, 
		{"JellemzokLabel_text", "Jellemz\u0151i:"}, 
		{"OsztasJellemzoLabel_text", "Osztandó lapok:"}, 
		{"PakliJellemzoLabel_text", "Pakli:"}, 
		{"JatekKiszallButton_label", "Kiszáll"}, 
		{"JatekosListaButton_label", "<< Játékoslista"}, 
		{"CardHelpPopupMenu_label", "KártyaSúgó"}, 
		{"SzinSugoMenuItem_label", "SzínSúgó"}, 
		{"JelzesSugoMenuItem_label", "JelzésSúgó"}, 
		{"ResolveMenuItem_label", "Milyenné válna?"}, 
		{"RejectDialog_title", "Figyelem!"}, 
		{"RejectOKButton_label", "OK"}, 
		{"ÚJ_ABLAK", "ÚJ ABLAK"}, 
		{"Child_VCardApplet_#%n", "Child VCardApplet #%n"}, 
		{"KezdButton_label", "Kezd"}, 
		{"BefejezButton_label", "Befejez"}, 
		{"SorozButton_label", "Soroz"}, 
		{"BeszúrButton_label", "Beszúr"}, 
		{"VétóButton_label", "Vétó!"}, 
		{"KérButton_label", "Kér"}, 
		{"SemmiButton_label", "Semmi"}, 
		{"VálasztButton_label", "Választ"}, 
		{"(...)", "(...)"}, 
		{"SzinSugoMenuItem_label%c", "SzínSúgó - %c"}, 
		{"JelzesSugoMenuItem_label%j", "JelzésSúgó - %j"}, 
		{"<-_Klasszikus__->", "<- Klasszikus: ->"}, 
		{"Magyar", "Magyar"}, 
		{"Szlovák", "Szlovák"}, 
		{"Román", "Román"}, 
		{"<-_Mini__->", "<- Mini: ->"}, 
		{"Százas", "Százas"}, 
		{"Mini", "Mini"}, 
		{"Mini_R", "Mini_R"}, 
		{"<-_Maxi__->", "<- Maxi: ->"}, 
		{"Maxi", "Maxi"}, 
		{"Maxi_R", "Maxi_R"}, 
		{"<-_Extrém__->", "<- Extrém: ->"}, 
		{"Hazárd_R", "Hazárd_R"}, 
		{"PlayerList_%l_lap", "%l lap"}, 
		{"HalmozButton_label", "Halmoz"}, 
		{"PakliDescrButtonText", "?"}, 
		{"GameHelpPopupMenu_Label", "JátékSúgó"}, 
		{"WhatToDoMenuItem_label", "Mit tehetünk most?"}, 
	};
protected Object[][] getContents() {
	return contents;
}
}
